name: $(Date:yyyyMMdd)

trigger:
- dailydownload
pr: none
resources:
- repo: self

variables:
  ADO_BUILD: $(Build.BuildId)
  BUILD_DATE: $(Build.BuildNumber)
  vmImageName: 'ubuntu-latest'

stages:
- stage: GenerateCSV
  displayName: Generate CSV and copy to blob storage


  jobs:
  - job: run_script
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          npm install json2csv mongodb
          node ./scripts/generateCSV.js
  # - job:

  # - job: copy_csv
  #   pool:
  #     vmImage: $(vmImageName)
  #   dependsOn: run_script
  #   steps:
    
  #   - task: AzureCLI@2
  #     inputs:
  #       azureSubscription: $(AZURE_SUBSCRIPTION)
  #       scriptType: 'bash'
  #       scriptLocation: 'inlineScript'
  #       inlineScript: |
  #         azcopy login --serviceprinicple
  #         azcopy copy './users.csv' 'https://alphasitesadev.blob.core.windows.net/alphasite/users.csv'
    
        
