name: $(Date:yyyyMMdd)

trigger:
- dailydownload
pr: none
resources:
- repo: self

variables:
  MONGO_URL: $(MONGO_URL)
  MONGO_DB: $(MONGO_DB)
  ADO_BUILD: $(Build.BuildId)
  BUILD_DATE: $(Build.BuildNumber)
  vmImageName: 'vs2017-win2016'

stages:
- stage: GenerateCSV
  displayName: Generate CSV and copy to blob storage


  jobs:
  - job: run_script
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ls ./
          node ./lib/generateCSV.js

  - job: copy_csv
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureFileCopy@4
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        storage: $(AZURE_STORAGE)
        SourcePath: './users.csv'
        Destination: 'AzureBlob'
        ContainerName: 'alphasite'
