name: $(Date:yyyyMMdd)

trigger:
- dailydownload
pr: none
resources:
- repo: self

variables:
  MONGO_URL: $(MONGO_URL)
  MONGO_DB: $(MONGO_DB)
  ADO_BUILD: $(Build.BuildId)
  BUILD_DATE: $(Build.BuildNumber)

stages:
- stage: Nodejs
  displayName: Install Node.js and run script

  jobs:
  - job: install_node
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'

  - job: run_script
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'node ./lib/generateCSV.js'
