name: $(Date:yyyyMMdd)

trigger:
- dailydownload
pr: none
resources:
- repo: self

variables:
  imageRepository: 'alphasite'
  ADO_BUILD: $(Build.BuildId)
  BUILD_DATE: $(Build.BuildNumber)
  tag: 'ADO-$(ADO_BUILD)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: HelloWorld
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
      
          echo 'Hello world'