name: $(Date:yyyyMMdd)

trigger: none # stop pipeline from running on commits
pr: none # stop pipeline on running from PRs

schedules:
  - cron: "0 0 * * *"
    displayName: Daily email
    branches:
      include:
        - main
    always: true

resources:
  - repo: self

stages:
  - stage: Email
    displayName: Generate csv and send email
    jobs:
      - job: Email
        displayName: Generate csv and send email
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                curl -H "Authorization: $(CSV_AUTH_KEY)" $(CSV_API)
