name: Testing and Linting 🧪📝
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Install 🔧
        run: npm install

      - name: Linting Test 📝
        run: npm run lint:test
        env:
          CI: true